app:
  kuda-go-url: "https://kudago.com/public-api/v1.4"
  categories-endpoint: "/place-categories/"
  locations-endpoint: "/locations/"
  events-endpoint: "/events/"
  threads: 16
  scheduler-period: 3600
