app:
  kuda-go-url: "https://kudago.com/public-api/v1.4"
  categories-endpoint: "/place-categories/"
  locations-endpoint: "/locations/"

currency-app:
  bank-api-url: "https://www.cbr.ru/scripts"
  cache-eviction-interval: 3600000

resilience4j.circuitbreaker:
  instances:
    bankClient:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  health:
    circuitbreakers:
      enabled: true
    show-details: always
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
