app:
  kuda-go-url: "https://kudago.com/public-api/v1.4"
  categories-endpoint: "/place-categories/"
  locations-endpoint: "/locations/"

currency-app:
  bank-api-url: "https://www.cbr.ru/scripts"
  cache-eviction-interval: 3600000