name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - fj_2024_lesson_14
  pull_request:
    branches:
      - main
      - fj_2024_lesson_14
    paths:
      - .github/workflows/fintech.yml

permissions:
  packages: write
  pull-requests: write

jobs:
  build:
    permissions:
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build --refresh-dependencies

  # Stage 2: Static Code Analysis
  static_analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run static code analysis
        run: ./gradlew check

  # Stage 3: Docker Build and Push
  docker:
    permissions:
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: static_analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --refresh-dependencies

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/stukenvitalii/fintech:latest .  # Tag for GitHub Container Registry

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/stukenvitalii/fintech:latest

  # Stage 4: Coverage Report
  coverage_report:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Coverage
        run: ./gradlew jacocoTestReport

      - name: Upload Jacoco Coverage Report
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true

  post_pr_comment:
    runs-on: ubuntu-latest
    needs: coverage_report
    steps:
      - name: Get Pull Request associated with push
        id: pr
        run: |
          PR_NUMBER=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.sha }} | \
            jq '.[0].number')
          echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Comment on Pull Request
        if: steps.pr.outputs.pr_number != ''
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = '${{ steps.pr.outputs.pr_number }}';
            const comment = 'This is an automated comment from GitHub Actions on your PR';
            const issueComment = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
            console.log(`Comment created at: ${issueComment.data.html_url}`);